lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: casinauser1_
      icon: mdi:script
      show_in_sidebar: true
      filename:  ./dashboards/energyEngineService/casinauser1_dashboard.yaml
# rssi switch is user defined and is not in package ! 
#following must be added to configuration.yaml
#homeassistant:
#  packages: !include_dir_named packages
python_script:
