automation casinauser1_anticipate:
  - alias: casinauser1_fv3_cmd_startAnticipate
    id: casinauser1_anticipate
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_start_ensavings
    condition: null
    action:
      - event: casinauser1_ws_fv3_cmd_startAnticipate
        event_data:
          state: fired
input_text:
  casinauser1_optimizing_fv:
    name: casinauser1_optimizing_fv_
    initial: "0"
  casinauser1_laststaterefresh:
    name: casinauser1_todo
    initial: "01012024"
  casinauser1_opirun:
    name: casinauser1_opirun_
    initial: "0"
  casinauser1_pgmrun:
    name: casinauser1_pgmrun_
    initial: "0"
  casinauser1_text1:
    name: Text 1
    initial: '{ "9:30" : 20, "16:00" : 18 }'
  casinauser1_text4:
    name: W/S
    initial: W
  casinauser1_text2:
    name: Text 2
    initial: ' {"9:20": 45 , "16:30":10}'
  casinauser1_destemp:
    name: destemp
    initial: ' {"9:20": 45 , "16:30":10}'
automation casinauser1_rssi:
  - alias: casinauser1_ws
    id: casinauser1_ws_
    trigger:
      - platform: event
        event_type: ws_event
        event_data:
          data: "1"
    condition: null
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.rssi
  - alias: casinauser1_scaldabagnoev
    id: casinauser1_scaldabagnoev_
    trigger:
      - platform: event
        event_type: casinauser1_scaldabagno_event
        event_data:
          data: "1"
    condition: null
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.scaldabagno
  - alias: casinauser1_scaldabagnoevoff
    id: casinauser1_scaldabagnoev_off
    trigger:
      - platform: event
        event_type: scaldabagno_event_off
        event_data:
          data: na
    condition: null
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.scaldabagno
  - alias: casinauser1_prgm_state_mainev
    id: casinauser1_prgm_state_mainev_
    trigger:
      - platform: event
        event_type: casinauser1_prgm_state_main
        event_data:
          val: true
    condition: null
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.acssw
  - alias: casinauser1_prgm_state_mainevoff
    id: casinauser1_prgm_state_mainevoff_
    trigger:
      - platform: event
        event_type: casinauser1_prgm_state_main
        event_data:
          val: false
    condition: null
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.acssw
  - alias: casinauser1_setmanual_rssi_on
    id: casinauser1_setmanual_rssi_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_setmanual_rssi_on_but
    condition: null
    action:
      - event: casinauser1_ws_setmanual_rssi_on
        event_data:
          state: fired
  - alias: casinauser1_setmanual_rssi_off
    id: casinauser1_setmanual_rssi_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_setmanual_rssi_off_but
    condition: null
    action:
      - event: casinauser1_ws_setmanual_rssi_off
        event_data:
          state: fired
input_button:
  casinauser1_setmanual_rssi_on_but:
    name: casinauser1_setmanual_rssi_on_but
    icon: mdi:bell
  casinauser1_setmanual_rssi_off_but:
    name: casinauser1_setmanual_rssi_off_but
    icon: mdi:bell
  casinauser1_start_savingservice:
    name: casinauser1_start_optimazing_service
    icon: mdi:bell
  casinauser1_stop_savingservice:
    name: casinauser1_stop_optimazing_service
    icon: mdi:bell
  casinauser1_start_progservice:
    name: casinauser1_start_programming_service
    icon: mdi:bell
  casinauser1_stop_progservice:
    name: casinauser1_stop_programming_service
    icon: mdi:bell
  casinauser1_setmanual_acs_on_but:
    name: casinauser1_setmanual_acs_on_but
    icon: mdi:bell
  casinauser1_setmanual_acs_off_but:
    name: casinauser1_setmanual_acs_off_but
    icon: mdi:bell
climate:
  - platform: generic_thermostat
    name: casinauser1_termostato_locale
    heater: switch.rssi
    target_sensor: sensor.shelly_ht_temp
    min_temp: 10
    max_temp: 21
    ac_mode: false
    target_temp: 17
    cold_tolerance: 0.4
    hot_tolerance: 0
    min_cycle_duration:
      seconds: 30
    initial_hvac_mode: "off"
    away_temp: 16
automation casinauser1_interface:
  - alias: casinauser1_startoptimizing_service
    id: casinauser1_strantserv
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_start_savingservice
    condition: "{{ states.input_text.casinauser1_opirun.state == 'OFF'}}"
    action:
      - event: casinauser1_ws_startoptimizing_service
        event_data:
          state: fired
  - alias: casinauser1_stopoptimizing_service
    id: casinauser1_stopantserv
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_stop_savingservice
    condition: "{{ states.input_text.casinauser1_opirun.state == 'ON'}}"
    action:
      - event: casinauser1_ws_stopoptimizing_service
        event_data:
          state: fired
  - alias: casinauser1_startprogramming_service
    id: casinauser1_strpgmserv
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_start_progservice
    condition: "{{ states.input_text.casinauser1_pgmrun.state == 'OFF'}}"
    action:
      - event: casinauser1_ws_startprogramming_service
        event_data:
          state: fired
  - alias: casinauser1_stopprogramming_service
    id: casinauser1_stoppgmserv
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_stop_progservice
    condition: "{{ states.input_text.casinauser1_pgmrun.state == 'ON'}}"
    action:
      - event: casinauser1_ws_stopprogramming_service
        event_data:
          state: fired
automation casinauser1_sensor:
  - alias: casinauser1_setmanual_acs_on
    id: casinauser1_setmanual_acs_on
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_setmanual_acs_on_but
    condition: null
    action:
      - event: casinauser1_ws_setmanual_acs_on
        event_data:
          state: fired
  - alias: casinauser1_setmanual_acs_off
    id: casinauser1_setmanual_acs_off
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_button.casinauser1_setmanual_acs_off_but
    condition: null
    action:
      - event: casinauser1_ws_setmanual_acs_off
        event_data:
          state: fired
input_number:
  casinauser1_hour:
    name: ore
    initial: 1
    min: 1
    max: 24
    step: 1
    mode: box
  casinauser1_box1:
    name: minPower
    initial: 30
    min: -20
    max: 35
    step: 1
    mode: box
  casinauser1_battery:
    name: ore
    initial: 0
    min: 0
    max: 100
    unit_of_measurement: 0/0
    mode: box
  casinauser1_inverter:
    name: inverter
    initial: 0
    min: 0
    max: 20
    unit_of_measurement: P
    mode: box
template:
  - sensor:
      - name: casinauser1_pippo
        state: '[4,20,2,{"FVPower":{{ states.input_number.casinauser1_box1.state|int }}}]'
        icon: mdi:tools
  - sensor:
      - name: casinauser1_startprogrammer
        unique_id: casinauser1_strpgm
        state: '[1,23,3, { "PGMgiorno" : {{ states.input_text.casinauser1_text1.state }} , "PGMacs" : {{ states.input_text.casinauser1_text2.state }} ,   "TgiornoTollerance" : "2" ,"ei":"{{ states.input_text.casinauser1_text4.state }}"} ]'
        icon: mdi:tools
